#!/usr/bin/env python3
"""Print the real environment-discovery facts for docs/environment.md.

Run this on a Gentoo host (the gumbo runner or a stage3 chroot); the output is
committed verbatim. Everything comes from the supported portage API.
"""

import platform
import sys
from pathlib import Path


def layout(path: Path) -> str:
    if path.is_dir():
        return "directory"
    if path.is_file():
        return "file"
    return "absent"


def main() -> int:
    import portage

    settings = portage.settings
    config_root = Path(settings["PORTAGE_CONFIGROOT"])
    portage_dir = config_root / "etc" / "portage"

    facts = {
        "PYTHON_VERSION": platform.python_version(),
        "PORTAGE_VERSION": portage.VERSION,
        "PORTAGE_MODULE": str(Path(portage.__file__).parent),
        "ROOT": settings["ROOT"],
        "EPREFIX": settings.get("EPREFIX", ""),
        "PORTAGE_CONFIGROOT": str(config_root),
        "ARCH": settings.get("ARCH", ""),
        "ACCEPT_KEYWORDS": settings.get("ACCEPT_KEYWORDS", ""),
        # PORTAGE_PROFILE is only set inside an ebuild environment; the resolved
        # profile lives on the config object itself.
        "PROFILE": str(Path(getattr(settings, "profile_path", "") or ".").resolve()),
        "PROFILE_STACK": str(len(getattr(settings, "profiles", ()))),
        "PACKAGE_USE_LAYOUT": layout(portage_dir / "package.use"),
        "PACKAGE_KEYWORD_LAYOUT": layout(portage_dir / "package.accept_keywords"),
        "LEGACY_PACKAGE_KEYWORDS": layout(portage_dir / "package.keywords"),
        "MANAGED_USE_TARGET": str(portage_dir / "package.use" / "ptools"),
        "MANAGED_KEYWORD_TARGET": str(portage_dir / "package.accept_keywords" / "ptools"),
        "EBUILD_REPOSITORIES": " ".join(sorted(settings.repositories.prepos_order)),
        "PACKAGES_IN_TREE": str(len(portage.portdb.cp_all())),
    }

    print("# Environment Discovery")
    print()
    print("Generated by `scripts/discover_environment.py` on a real Gentoo host.")
    print()
    print("```yaml")
    for key, value in facts.items():
        print(f"{key}: {value or '(unset)'}")
    print("```")
    return 0


if __name__ == "__main__":
    sys.exit(main())
